
#directoy di output dove si trovano i files .page
PostPerPage = 46
PageSplitterInputDir = "./data/page-in"
PostSourceDir = "./data/post-src"
OutDirPage = "./data/test/src"
#OutDirPage = "D:\\Projects\\GItHub\\InvidositeHtmlgit\\src"
ServiceURL = "127.0.0.1:4201" 
#WebGenWebPageDir = "D:\\Projects\\GItHub\\InvidositeHtmlgit"
WebGenWebPageDir = "D:\\scratch\\go-lang\\vido-preproc\\data\\test"
WebGenLocation = "D:\\ruby\\ruby_2_3_1\\bin"
#WebgenOutIndexFile = "file:///D:/Projects/GItHub/InvidositeHtmlgit/out/snapshot/index.html"
WebgenOutIndexFile = "file:///D:/scratch/go-lang/vido-preproc/data/test/out/index.html"